### ISSUE TITLE
Allow scroll up while generation takes place

### ISSUE THREAD

**Issue by RahulVivekNair** [patrikzudel/PatrikZeros-ChatGPT-API-UI#23] opened 2023-03-22 09:04 UTC
- [x] I have read all open and **closed** Issues and confirm that this is not a duplicate.

#### PROBLEM:
When the api streams data to the interface, in the regular chatgpt UI from openai we are able to scroll up while generation takes place. Unfortunately, when trying to scroll up in this ui, it scroll back down when a new token is generated.

#### SOLUTION:
Allow scroll up while generation takes place while still scrolling down with new text generation only if the user hasn't scrolled up during generation.

**Comment by patrikzudel** [comment] 2023-03-22 09:48
Duplicate of #12
The title is better though so I will change the title of #12 
Thanks for your input!

**Closed as completed by patrikzudel** 2023-03-22 09:48 UTC
Labels: feature-request
