### ISSUE TITLE
The model: GPT4 does not exist

### ISSUE THREAD

**Issue by xdsai** [patrikzudel/PatrikZeros-ChatGPT-API-UI#28] opened 2023-04-14 18:18 UTC
- [x] I have read all open and **closed** Issues and confirm that this is not a duplicate.

**Describe the bug**
When GPT4-8k or GPT4-32k is selected in the settings menu, and a message is sent, the system responds with a message that "gpt-4 does not exist" or "gpt4-32k does not exist"

**To Reproduce**
1. Go to settings in the bottom right
2. Choose either of the two GPT4 models
3. Send a message
4. System responds with - The model: GPT4 does not exist

**Expected behavior**
GPT4 is supposed to reply as expected

**Screenshots**
![image](https://user-images.githubusercontent.com/49403617/232125228-b76b6f7d-44b4-4cf8-875d-d4074114c4bf.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Firefox
 - Version 111

**Additional context**
GPT3.5 Turbo works as expected.

**Comment by patrikzudel** [comment] 2023-04-14 19:07
Duplicate of #27 :(

You need access granted from OpenAI to use the GPT-4 API, it is not public yet.

**Closed as completed by patrikzudel** 2023-04-14 19:07 UTC
Labels: bug
